config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
      get "cart", :to => "shopping_carts#index"
      post "cart/create", :to => "shopping_carts#create"
      delete "cart", :to => "shopping_carts#destroy"
      get "mypage", :to => "users#mypage"
      get "mypage/edit", :to => "users#edit"
      get "mypage/address/edit", :to => "users#edit_address"
      put "mypage", :to => "users#update"
      get "mypage/edit_password", :to =>"users#edit_password"
      put "mypage/password", :to => "users#update_password"
      get  "mypage/favorite", :to => "users#favorite"
    end
  end
  
  resources :products do
    member do
      get :favorite
    end
    resources :reviews, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  acts_as_liker
  
  def update_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
 
    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/mailer.rb
class Users::Mailer < Devise::Mailer
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end
  
  def verify
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(
       :sign_up, keys: [ :name, :postal_code, :address, :phone, :email, :password, :password_confirmation ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
     devise_parameter_sanitizer.permit(
       :account_update, keys: [ :name, :postal_code, :address, :phone, :email, :password, :password_confirmation ])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    verify_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  def after_sign_in_path_for(user)
     products_path
  end
 
  def after_sign_out_path_for(user)
    root_path
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [ :name, :postal_code, :address, :phone, :email, :password, :password_confirmation ])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!
  
  def edit
  end

  def update
    @user.update_without_password(user_params)
    redirect_to mypage_users_url
  end

  def mypage
  end
  
  def edit_address
  end
  
  def update_password
    if password_set?
      @user.update_password(user_params) 
      flash[:notice] = "パスワードは正しく更新されました。"
      redirect_to root_url
    else
      @user.errors.add(:password, "パスワードに不備があります。")
      render "edit_password"
    end
  end
  
  def edit_password
  end
  
  def favorite
    @favorites = @user.likees(Product)
  end
  
  private
    def set_user
      @user = current_user
    end
  
    def user_params
      params.permit(:name, :email, :address, :phone, :password, :password_confirmation)
    end
    
    def password_set?
      user_params[:password].present? && user_params[:password_confirmation].present? ?
      true : false
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <span>
        <%= link_to "マイページ", mypage_users_path %> > 会員情報の編集
      </span>

      <h1 class="mt-3 mb-3">会員情報の編集</h1>

      <hr>

      <%= form_with url: mypage_users_path, local: true, method: :put do |f| %>
      
        
        <div class="form-group">
          <div class="d-flex justify-content-between">
            <%= f.label :name, "氏名", class: "text-md-left samazon-edit-user-info-label" %>
            <span onclick="switchEditUserInfo('.userName', '.editUserName', '.userNameEditLabel');" class="userNameEditLabel user-edit-label">
              編集
            </span>
          </div>
          <div class="collapse show userName">
            <h1 class="samazon-edit-user-info-value"><%= @user.name %></h1>
          </div>
          <div class="collapse editUserName">
            <%=
              f.text_field :name,
              class: "form-control #{"is-invalid" if @user.errors.messages[:name].present? } ",
              value: @user.name,
              autofocus: "true",
              required: "",
              autocomplete: "name",
              placeholder: "名前を入力"
            %>

            <%= f.submit "保存", class: "btn samazon-submit-button mt-3 w-25" %>

            <% if @user.errors.messages[:name].present? %>
            <span class="invalid-feedback" role="alert">
              <strong>氏名を入力してください</strong>
            </span>
            <% end %>
          </div>
        </div>

        <hr>

        <div class="form-group">
          <div class="d-flex justify-content-between">
            <%= f.label :email, "メールアドレス", class: "text-md-left samazon-edit-user-info-label" %>
            <span onclick="switchEditUserInfo('.userMail', '.editUserMail', '.userMailEditLabel');" class="userMailEditLabel user-edit-label">
              編集
            </span>
          </div>
          <div class="collapse show userMail">
            <h1 class="samazon-edit-user-info-value"><%= @user.email %></h1>
          </div>
          <div class="collapse editUserMail">
            <%=
              f.email_field :email,
              class: "form-control #{"is-invalid" if @user.errors.messages[:email].present? }",
              autofocus: "true",
              required: "",
              value: @user.email,
              autocomplete: "email",
              placeholder: "メールアドレスを入力"
            %>

            <%= f.submit "保存", class: "btn samazon-submit-button mt-3 w-25" %>

            <% if @user.errors.messages[:email].present? %>
            <span class="invalid-feedback" role="alert">
              <strong>メールアドレスを入力してください</strong>
            </span>
            <% end %>
          </div>
        </div>

        <hr>

        <div class="form-group">
          <div class="d-flex justify-content-between">
            <%= f.label :phone, "電話番号", class: "text-md-left samazon-edit-user-info-label" %>
            <span onclick="switchEditUserInfo('.userPhone', '.editUserPhone', 'userPhoneEditLabel');" class="userPhoneEditLabel user-edit-label">
              編集
            </span>
          </div>
          <div class="collapse show userPhone">
            <h1 class="samazon-edit-user-info-value"><%= @user.phone %></h1>
          </div>
          <div class="collapse editUserPhone">
          <%= 
            f.text_field :phone,
            class: "form-control #{"is-invalid" if @user.errors.messages[:phone].present? }",
            value: @user.phone,
            autocomplete: "phone",
            placeholder: "XXX-XXXX-XXXX"
          %>

          <%= f.submit "保存", class: "btn samazon-submit-button mt-3 w-25" %>

          <% if @user.errors.messages[:phone].present? %>
          <span class="invalid-feedback" role="alert">
            <strong>電話番号を入力してください</strong>
          </span>
          <% end %>
        </div>
      </div>

      <hr>

      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
    let switchEditUserInfo = (textClass, inputClass, labelClass) => {
        if ($(textClass).css('display') == 'block') {
            $(labelClass).text("キャンセル");
            $(textClass).collapse('hide');
            $(inputClass).collapse('show');
        } else {
            $(labelClass).text("編集");
            $(textClass).collapse('show');
            $(inputClass).collapse('hide');
        }
    }
</script>

app/views/users/edit_address.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <span>
        <%= link_to "マイページ", mypage_users_path  %> > お届け先変更
      </span>
      <h3 class="mt-3 mb-3">お届け先変更</h3>

        <hr>

        <%= form_with model: @user, url: mypage_users_path, local: true, method: :put do |f| %>
        <div class="form-group row">

          <%= f.label :name, "", class: "col-md-5 col-form-label text-md-left" do %>
            氏名
            <span class="ml-1 samazon-require-input-label">
              <span class="samazon-require-input-label-text">必須</span>
            </span>
          <% end %>

          <div class="col-md-7">
            <%=
              f.text_field :name,
              class: "form-control #{"is-invalid" if @user.errors.messages[:name].present? } samazon-login-input",
              autofocus: "true",
              required: "",
              autocomplete: "name",
              placeholder: "侍 太郎"
            %>

            <% if @user.errors.messages[:name].present? %>
              <span class="samazon-error-message">
                <strong><%= @user.errors.full_messages_for(:name).first %></strong>
              </span>
            <% end %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :postal_code, "", class: "col-md-5 col-form-label text-md-left" do %>
          郵便番号
            <span class="ml-1 samazon-require-input-label">
              <span class="samazon-require-input-label-text">必須</span>
            </span>
          <% end %>

          <div class="col-md-7">
            <%=
              f.text_field :postal_code,
              class: "form-control #{"is-invalid" if @user.errors.messages[:postal_code].present? } samazon-login-input",
              required: "",
              placeholder: "150-0043"
            %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :address, "", class: "col-md-5 col-form-label text-md-left" do %>
          住所
            <span class="ml-1 samazon-require-input-label">
              <span class="samazon-require-input-label-text">必須</span>
            </span>
          <% end %>

          <div class="col-md-7">
            <%=
              f.text_field :address,
              class: "form-control #{"is-invalid" if @user.errors.messages[:address].present? } samazon-login-input",
              required: "",
              placeholder: "東京都渋谷区道玄坂２丁目１１−１"
            %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :phone, "", class: "col-md-5 col-form-label text-md-left" do %>
          電話番号
            <span class="ml-1 samazon-require-input-label">
              <span class="samazon-require-input-label-text">必須</span>
            </span>
          <% end %>

          <div class="col-md-7">
            <%=
              f.text_field :phone,
              class: "form-control #{"is-invalid" if @user.errors.messages[:phone].present? } samazon-login-input",
              required: "",
              placeholder: "03-5790-9039"
            %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, "", class: "col-md-5 col-form-label text-md-left" do %>
          メールアドレス
            <span class="ml-1 samazon-require-input-label">
              <span class="samazon-require-input-label-text">必須</span>
            </span>
          <% end %>

          <div class="col-md-7">
            <%=
              f.email_field :email,
              class: "form-control #{"is-invalid" if @user.errors.messages[:email].present? } samazon-login-input",
              autofocus: "true",
              required: "",
              autocomplete: "email",
              placeholder: "メールアドレス"
            %>

            <% if @user.errors.messages[:email].present? %>
              <span class="samazon-error-message">
                <strong><%= @user.errors.full_messages_for(:email).first %></strong>
              </span>
            <% end %>
          </div>
        </div>

        <hr>

        <div class="form-group d-flex justify-content-end">
          <%= f.submit "保存する", class: "btn samazon-submit-button w-25" %>
        </div>
      </form>
    </div>
  </div>
<% end %>
</div>

app/views/users/edit_password.html.erb
<div class="container">
  <%= form_with url: mypage_password_users_path, local: true, method: :put do |f| %>
    <div class="form-group row">
      <%= f.label :password, "新しいパスワード", class: "col-md-3 col-form-label text-md-right" %>

      <div class="col-md-7">
        <%=
          f.password_field :password,
          class: "form-control #{"is-invalid" if @user.errors.messages[:password].present? }",
          autocomplete: "new-password"
        %>

        <% if @user.errors.messages[:password].present? %>
          <span class="invalid-feedback" role="alert">
            <strong><%= @user.errors.messages[:password].first %></strong>
          </span>
        <% end %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :password_confirmation, "確認用", class: "col-md-3 col-form-label text-md-right" %>

      <div class="col-md-7">
        <%=
          f.password_field :password_confirmation,
          class: "form-control #{"is-invalid" if @user.errors.messages[:password_confirmation].present? }",
          autocomplete: "new-password"
        %>
      </div>
    </div>

    <div class="form-group d-flex justify-content-center">
      <button type="submit" class="btn btn-danger w-25">
        パスワード更新
      </button>
    </div>
  <% end %>
</div>

app/views/users/favorite.html.erb
<div class="container  d-flex justify-content-center mt-3">
  <div class="w-75">
    <h1>お気に入り</h1>

    <hr>

    <div class="row">
      <% @favorites.each do |favorite| %>
      <div class="col-md-8 mt-2">
        <div class="d-inline-flex">
          <%= link_to product_path(favorite), class: "w-25" do %>
            <%= image_tag "/images/dummy.png", class: "img-fuild w-100" %>
          <% end %>
          <div class="container mt-3">
            <h5 class="w-100 samazon-favorite-item-text"><%= favorite.name %></h5>
            <h6 class="w-100samazon-favorite-item-text">￥<%= favorite.price %></h6>
          </div>
        </div>
      </div>
      <div class="col-md-2 d-flex align-items-center justify-content-end">
        <%= link_to product_path(favorite), class: "samazon-favorite-item-delete" do %>
          削除
        <% end %>
      </div>
      <div class="col-md-2 d-flex align-items-center justify-content-end">
        <%= form_with url: cart_create_users_path, local: true do |f| %>
            <%= f.hidden_field :product_id, value: favorite.id %>
            <%= f.hidden_field :price, value: favorite.price %>
            <%= f.hidden_field :quantity, value: 1 %>
            <%= f.submit "カートに入れる", class: "btn samazon-favorite-add-cart text-white w-100" %>
          <% end %>
      </div>
      <% end %>
    </div>

    <hr>

  </div>
</div>

app/views/users/mypage.html.erb
<div class="container d-flex justify-content-center mt-3">
  <div class="w-50">
    
    <h1>マイページ</h1>

    <hr>

    <div class="container">
      <div class="d-flex justify-content-between">
        <div class="row">
          <div class="col-2 d-flex align-items-center">
            <i class="fas fa-user fa-3x"></i>
          </div>
          <div class="col-9 d-flex align-items-center ml-2 mt-3">
            <div class="d-flex flex-column">
              <label for="user-name">会員情報の編集</label>
              <p>アカウント情報の編集</p>
            </div>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <%= link_to mypage_edit_users_path do %>
            <i class="fas fa-chevron-right fa-2x"></i>
          <% end %>
        </div>
      </div>
    </div>

    <hr>

    <div class="container">
      <div class="d-flex justify-content-between">
        <div class="row">
          <div class="col-2 d-flex align-items-center">
            <i class="fas fa-archive fa-3x"></i>
          </div>
          <div class="col-9 d-flex align-items-center ml-2 mt-3">
            <div class="d-flex flex-column">
              <label for="user-name">注文履歴</label>
              <p>注文履歴を確認できます</p>
            </div>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <%= link_to mypage_users_path do %>
            <i class="fas fa-chevron-right fa-2x"></i>
          <% end %>
        </div>
      </div>
    </div>

    <hr>
    
    <div class="container">
      <div class="d-flex justify-content-between">
        <div class="row">
          <div class="col-2 d-flex align-items-center">
            <i class="fas fa-map-marked fa-3x"></i>
          </div>
          <div class="col-9 d-flex align-items-center ml-3 mt-3">
            <div class="d-flex flex-column">
              <label for="user-name">お届け先の変更</label>
              <p>登録住所の変更</p>
            </div>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <%= link_to mypage_address_edit_users_path do %>
            <i class="fas fa-chevron-right fa-2x"></i>
          <% end %>
        </div>
      </div>
    </div>
    
    <hr>
    
    <div class="container">
      <div class="d-flex justify-content-between">
        <div class="row">
          <div class="col-2 d-flex align-items-center">
            <i class="fas fa-lock fa-3x"></i>
          </div>
          <div class="col-9 d-flex align-items-center ml-3 mt-3">
            <div class="d-flex flex-column">
              <label for="user-name">パスワード変更</label>
              <p>パスワードを変更します</p>
            </div>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <%= link_to mypage_edit_password_users_path do %>
            <i class="fas fa-chevron-right fa-2x"></i>
          <% end %>
        </div>
      </div>
    </div>
 
    <hr>

    <div class="container">
      <div class="d-flex justify-content-between">
        <div class="row">
          <div class="col-2 d-flex align-items-center">
            <i class="fas fa-sign-out-alt fa-3x"></i>
          </div>
          <div class="col-9 d-flex align-items-center ml-2 mt-3">
            <div class="d-flex flex-column">
              <label for="user-name">ログアウト</label>
              <p>ログアウトします</p>
            </div>
          </div>
        </div>
        <div class="d-flex align-items-center">
          <%= link_to logout_path, method: :delete do %>
            <i class="fas fa-chevron-right fa-2x"></i>
          <% end %>          
        </div>
      </div>
    </div>

    <hr>

  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>