config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
      get "cart", :to => "shopping_carts#index"
      post "cart/create", :to => "shopping_carts#create"
      delete "cart", :to => "shopping_carts#destroy"
      get "mypage", :to => "users#mypage"
      get "mypage/edit", :to => "users#edit"
      get "mypage/address/edit", :to => "users#edit_address"
      put "mypage", :to => "users#update"
      get "mypage/edit_password", :to =>"users#edit_password"
      put "mypage/password", :to => "users#update_password"
      get  "mypage/favorite", :to => "users#favorite"
    end
  end
  
  resources :products do
    member do
      get :favorite
    end
    resources :reviews, only: [:create]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
  acts_as_likeable
  
  PER = 15
 
  scope :display_list, -> (page) { page(page).per(PER) }
  scope :on_category, -> (category) { where(category_id: category) }
   scope :sort_order, -> (order) { order(order) }
 
   scope :category_products, -> (category, page) { 
     on_category(category).
     display_list(page)
   }
 
   scope :sort_products, -> (sort_order, page) {
     on_category(sort_order[:sort_category]).
     sort_order(sort_order[:sort]).
     display_list(page)
   }
  scope :sort_list, -> { 
     {
       "並び替え" => "", 
       "価格の安い順" => "price asc",
       "価格の高い順" => "price desc", 
       "出品の古い順" => "updated_at asc", 
       "出品の新しい順" => "updated_at desc"
     }
   }
  
  def reviews_new
    reviews.new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :favorite]
  
  def index
     if sort_params.present?
      @sorted = sort_params[:sort]
      @category = Category.request_category(sort_params[:sort_category])
      @products = Product.sort_products(sort_params, params[:page])
    elsif params[:category].present?
      @category = Category.request_category(params[:category])
      @products = Product.category_products(@category, params[:page])
    else
      @products = Product.display_list(params[:page])
    end
    
     @categories = Category.all
     @major_category_names = Category.major_categories
     @sort_list = Product.sort_list
  end

  def show
    @reviews = @product.reviews
    @review = @reviews.new
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to product_url @product
  end

  def edit
    @categories = Category.all
  end

  def update
    @product.update(product_params)
    redirect_to product_url @product
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end
  
  def favorite
    current_user.toggle_like!(@product)
    redirect_to product_url @product
  end
  
  private
  
    def set_product
       @product = Product.find(params[:id])
    end
    
    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id)
    end
    
    def sort_params
      params.permit(:sort, :sort_category)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="container">
  <h1>商品情報更新</h1>

  <%= form_with model: @product do |f| %>
    <div class="form-group">
      <%= f.label "商品名" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "商品説明" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "価格" %>
      <%= f.number_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label "カテゴリ" %>
      <%= f.select :category_id, Category.all.map { |category| [category.name, category.id] }, {}, class: "form-control" %>
    </div>
    <%= f.submit "更新", class: "btn btn-danger" %>
  <% end %>

  <%= link_to "商品一覧に戻る", products_path %>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col-2">
    <%= render partial: "layouts/sidebar", locals: { categories: @categories, major_category_names: @major_category_names } %>
  </div>
  <div class="col-9">
    <div class="container">
      <% if @category.present? %>
        <%= link_to "トップ", "#", category: @major_category_name %> > <%= @category.name %>
        <h1><%= @category.name %>の商品一覧<%= @products.count %>件</h1>
        <%= form_with url: products_path, method: :get, local: true, class: "form-inline" do |f| %>
          <%= f.hidden_field :sort_category, value: @category.id %>
          並び替え
          <% if @sorted.present? %>
            <%= f.select :sort, @sort_list, { selected: @sorted }, onChange: "javascript: this.form.submit();", class: "form-inline ml-2" %>
          <% else %>
            <%= f.select :sort, @sort_list, {}, onChange: "javascript: this.form.submit();", class: "form-inline ml-2" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="container mt-4">
      <div class="row w-100">

        <% @products.each do |product|%>
        <div class="col-3">
          <%= link_to product_path(product) do %>
            <%= image_tag "/images/dummy.png", class: "img-thumbnail"%>
          <% end %>
          <div class="row">
            <div class="col-12">
              <p class="samazon-product-label mt-2">
                <%= product.name %><br>
                <label>¥<%= product.price %></label>
              </p>
            </div>
          </div>
        </div>
        <% end %>

      </div>
    </div>
    <%= paginate @products %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h1>新しい商品を追加</h1>

    <%= form_with model: @product do |f| %>
      <div class="form-group">
        <%= f.label "商品名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label "商品説明" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label "価格" %>
        <%= f.number_field :price, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label "カテゴリ" %>
        <%= f.select :category_id, Category.all.map { |category| [category.name, category.id] }, {}, class: "form-control" %>
      </div>

      <%= f.submit "商品を登録", class:"btn btn-success" %>
    <% end %>

    <%= link_to "商品一覧に戻る", products_path %>
</div>

app/views/products/show.html.erb
<div class="d-flex justify-content-center">
  <div class="row w-75">
    <div class="col-5 offset-1">
      <%= image_tag "/images/dummy.png", class: "w-100 img-fuild" %>
    </div>

    <div class="col">
      <div class="d-flex flex-column">
        <h1 class="">
          <%= @product.name %>
        </h1>
        <p class="">
          <%= @product.description %>
        </p>
        <hr>
        <p class="d-flex align-items-end">
          ￥<%= @product.price %>（税込）
        </p>
        <hr>
      </div>

      <% if user_signed_in? %>
        <%= form_with url: cart_create_users_path, local: true do |f| %>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.hidden_field :name, value: @product.name %>
          <%= f.hidden_field :price, value: @product.price %>
          <div class="form-group row">
            <%= f.label "数量", class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
              <%= f.number_field :quantity, min:1, value:1, class: "form-control w-25"%>
            </div>
          </div>
          <div class="row">
            <div class="col-7">
              <%= f.submit "カートに追加", class: "btn samazon-submit-button w-100" do %>
                <i class="fas fa-shopping-cart"></i>
              <% end %>
            </div>
            <div class="col-5">
              <%= link_to favorite_product_path, class: "btn samazon-favorite-button text-favorite w-100" do %>
                <i class="fa fa-heart"></i><%= current_user.likes?(@product) ? "お気に入り解除" : "お気に入り" %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>

    <div class="offset-1 col-11">
      <hr class="w-100">
      <h3 class="float-left">カスタマーレビュー</h3>
    </div>

    <div class="offset-1 col-10">
      <div class="row">
        <% @reviews.each do |review| %>
        <div class="offset-md-5 col-md-5">
          <p class="h3"><%= review.content %></p>
          <label><%= review.created_at %></label>
        </div>
        <% end %>
      </div>
 
      <% if user_signed_in? %>
        <div class="row">
          <div class="offset-md-5 col-md-5">
            <%= form_with model: @review, url: product_reviews_path(@product) do |f| %>
              <%= f.text_area :content, class: "form-control m-2" %>
              <%= f.submit "レビューを追加" , class:"btn samazon-submit-button ml-2"%>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>