config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
      get "cart", :to => "shopping_carts#index"
      post "cart/create", :to => "shopping_carts#create"
      delete "cart", :to => "shopping_carts#destroy"
      get "mypage", :to => "users#mypage"
      get "mypage/edit", :to => "users#edit"
      get "mypage/address/edit", :to => "users#edit_address"
      put "mypage", :to => "users#update"
      get "mypage/edit_password", :to =>"users#edit_password"
      put "mypage/password", :to => "users#update_password"
      get  "mypage/favorite", :to => "users#favorite"
    end
  end
  
  resources :products do
    member do
      get :favorite
    end
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    
    scope :major_categories, -> { pluck(:major_category_name).uniq }
    scope :request_category, -> (category) { find(category.to_i) }
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
  acts_as_likeable
  
  PER = 15
 
  scope :display_list, -> (page) { page(page).per(PER) }
  scope :on_category, -> (category) { where(category_id: category) }
   scope :sort_order, -> (order) { order(order) }
 
   scope :category_products, -> (category, page) { 
     on_category(category).
     display_list(page)
   }
 
   scope :sort_products, -> (sort_order, page) {
     on_category(sort_order[:sort_category]).
     sort_order(sort_order[:sort]).
     display_list(page)
   }
  scope :sort_list, -> { 
     {
       "並び替え" => "", 
       "価格の安い順" => "price asc",
       "価格の高い順" => "price desc", 
       "出品の古い順" => "updated_at asc", 
       "出品の新しい順" => "updated_at desc"
     }
   }
  
  def reviews_new
    reviews.new
  end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :product
    belongs_to :user
    
    def save_review(review, review_params)
    review.content = review_params[:content]
    review.user_id = review_params[:user_id]
    review.product_id = review_params[:product_id]
    save
  end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  acts_as_shopping_cart
  
  scope :set_user_cart, -> (user) { user_cart = where(user_id: user.id, buy_flag: false)&.last
                               user_cart.nil? ? ShoppingCart.create(user_id: user.id)
                                              : user_cart }


  def tax_pct
    0
  end
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ApplicationRecord
  acts_as_shopping_cart_item
  scope :user_cart_items, -> (user_shoppingcart) { where(owner_id: user_shoppingcart) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  acts_as_liker
  
  def update_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
 
    result = update(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :favorite]
  
  def index
     if sort_params.present?
      @sorted = sort_params[:sort]
      @category = Category.request_category(sort_params[:sort_category])
      @products = Product.sort_products(sort_params, params[:page])
    elsif params[:category].present?
      @category = Category.request_category(params[:category])
      @products = Product.category_products(@category, params[:page])
    else
      @products = Product.display_list(params[:page])
    end
    
     @categories = Category.all
     @major_category_names = Category.major_categories
     @sort_list = Product.sort_list
  end

  def show
    @reviews = @product.reviews
    @review = @reviews.new
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to product_url @product
  end

  def edit
    @categories = Category.all
  end

  def update
    @product.update(product_params)
    redirect_to product_url @product
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end
  
  def favorite
    current_user.toggle_like!(@product)
    redirect_to product_url @product
  end
  
  private
  
    def set_product
       @product = Product.find(params[:id])
    end
    
    def product_params
      params.require(:product).permit(:name, :description, :price, :category_id)
    end
    
    def sort_params
      params.permit(:sort, :sort_category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    review = product.reviews_new
    review.save_review(review, review_params)
    redirect_to product_url(product)
  end
  
  private
    def review_params
      params.require(:review).permit(:content).
             merge(user_id: current_user.id, product_id: params[:product_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!
  
  def edit
  end

  def update
    @user.update_without_password(user_params)
    redirect_to mypage_users_url
  end

  def mypage
  end
  
  def edit_address
  end
  
  def update_password
    if password_set?
      @user.update_password(user_params) 
      flash[:notice] = "パスワードは正しく更新されました。"
      redirect_to root_url
    else
      @user.errors.add(:password, "パスワードに不備があります。")
      render "edit_password"
    end
  end
  
  def edit_password
  end
  
  def favorite
    @favorites = @user.likees(Product)
  end
  
  private
    def set_user
      @user = current_user
    end
  
    def user_params
      params.permit(:name, :email, :address, :phone, :password, :password_confirmation)
    end
    
    def password_set?
      user_params[:password].present? && user_params[:password_confirmation].present? ?
      true : false
    end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  def index
    if sort_params.present?
      @category = Category.request_category(sort_params[:sort_category])
      @products = Product.sort_products(sort_params, params[:page])
    elsif params[:category].present?
      @category = Category.request_category(params[:category])
      @products = Product.category_products(@category, params[:page])
    else
      @products = Product.display_list(params[:page])
    end
 
    @major_category_names = Category.major_categories
    @categories = Category.all
  end
  
  private
    def sort_params
      params.permit(:sort, :sort_category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/web_helper.rb
module WebHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm fixed-bottom mt-5">
  <%= link_to root_path, class: "navbar-brand mx-auto" do %>
    <%= image_tag "/images/logo.jpg", class: "img-fuild" %>
  <% end %>
</nav>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm samazon-header-container">
    <%= link_to root_path do %>
      <%= image_tag "/images/logo.jpg" %>
    <% end %>
    <form class="form-inline">
      <div class="form-group">
        <input class="form-control samazon-header-search-input">
      </div>
      <div class="input-group">
        <button type="submit" class="btn samazon-header-search-button"><i class="fas fa-search samazon-header-search-icon"></i></button>
      </div>
    </form>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ml-auto mr-5 mt-2">
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %>
        <li class="nav-item mr-5">
          <%= link_to mypage_users_path, class: "nav-link" do %>
            <i class="fas fa-user mr-1"></i><label>マイページ</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to mypage_favorite_users_path, class: "nav-link" do %>
            <i class="far fa-heart"></i>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to cart_users_path, class: "nav-link" do %>
            <i class="fas fa-shopping-cart"></i>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item mr-5">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <label>新規登録</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %>
            <label>ログイン</label>
          <% end %>
        </li>
        <hr>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="far fa-heart"></i><% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="fas fa-shopping-cart"></i><% end %>
        </li>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="container">
  <% major_category_names.each do |major_category_name| %>
    <h2><%= major_category_name %></h2>
    <% categories.each do |category| %>
      <% if category.major_category_name == major_category_name %>
        <label class="samazon-sidebar-category-label">
          <%= link_to category.name, products_path(category: category.id) %>
        </label>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV["APP_NAME"] %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/b688e32bfa.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <main class="py-4 mb-5">
      <% if notice %><p class="alert alert-warning"><%= notice %></div><% end %>
      <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
      <%= yield %>
    </main>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/web/index.html.erb
<div class="row">
  <div class="col-2">
    <%= render partial: "layouts/sidebar", locals: { categories: @categories, major_category_names: @major_category_names } %>
  </div>
    <div class="col-9">
      <h1>おすすめ商品</h1>
      <div class="row">
        <div class="col-4">
          <%= link_to "#", class: "img-thumbnail" do %>
            <%= image_tag "/images/orange.png", class: "img-thumbnail"%>
          <% end %>
          <div class="row">
             <div class="col-12">
              <p class="samazon-product-label mt-2">
                旬のオレンジ詰め合わせ<br>
                <label>￥2000</label>
              </p>
            </div>
          </div>
        </div>
        <div class="col-4">
          <%= link_to "#", class: "img-thumbnail" do %>
            <%= image_tag "/images/pan.png", class: "img-thumbnail"%>
          <% end %>
          <div class="row">
            <div class="col-12">
              <p class="samazon-product-label mt-2">
                フライパン20cm 鉄製 業務用<br>
                <label>￥5000</label>
              </p>
            </div>
          </div>
        </div>

        <div class="col-4">
          <%= link_to "#", class: "img-thumbnail" do %>
            <%= image_tag "/images/meat.png", class: "img-thumbnail"%>
          <% end %>
          <div class="row">
            <div class="col-12">
              <p class="samazon-product-label mt-2">
                和牛ロース200g 2枚入り<br>
                <label>￥8200</label>
              </p>
            </div>
          </div>
        </div>

      </div>

      <h1>新着商品</h1>
      <div class="row">
        <div class="col-3">
          <%= link_to "#", class: "img-thumbnail" do %>
            <%= image_tag "/images/panasonic.png", class: "img-thumbnail"%>
          <% end %>
          <div class="row">
            <div class="col-12">
              <p class="samazon-product-label mt-2">
                掃除機本体 Panasonic<br>
                <label>￥15000</label>
              </p>
            </div>
          </div>
        </div>

        <div class="col-3">
          <%= link_to "#", class: "img-thumbnail" do %>
            <%= image_tag "/images/sofa.png", class: "img-thumbnail"%>
          <% end %>
          <div class="row">
            <div class="col-12">
              <p class="samazon-product-label mt-2">
              3人掛けソファー ブラウン<br>
              <label>￥35000</label>
            </p>
          </div>
        </div>
      </div>

      <div class="col-3">
        <%= link_to "#", class: "img-thumbnail" do %>
          <%= image_tag "/images/item.png", class: "img-thumbnail"%>
        <% end %>
        <div class="row">
          <div class="col-12">
            <p class="samazon-product-label mt-2">
              柔軟剤 詰め替え 2L<br>
              <label>￥1000</labiel>
            </p>
          </div>
        </div>
      </div>

      <div class="col-3">
        <%= link_to "#", class: "img-thumbnail" do %>
          <%= image_tag "/images/goods.png", class: "img-thumbnail"%>
        <% end %>
        <div class="row">
          <div class="col-12">
            <p class="samazon-product-label mt-2">
              食器 カトラリーセット1組<br>
              <label>￥2000</label>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>